name: Verify workflow

# Controls when the action will run.
on:
  workflow_call:
    outputs:
      status:
        description: The status of the job
        value: ${{ jobs.verify.outputs.status }}

jobs:
  verify:
    runs-on: ubuntu-latest

    outputs:
      status: ${{ job.status }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Step 1
        run: |
          echo "In step 1"
          exit 1

      - name: Step 2
        if: ${{ always() }}
        run: |
          echo "In step 2"
          exit 0
